### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by piotrpog** [born05/craft-colorextractor#1]
After installing this plugin, message appears:

```
Color Extractor has been added, but an error occurred when installing it.
yii\base\UnknownMethodException: Calling unknown method: craft\elements\db\AssetQuery::imageColor()
```
Plugins seems to be properly installed however, it shows up on settings/plugins list.

**Comment by roelvanhintum** [comment]
@piotrpog Did you create a color or plaintext field with the imageColor handle on the assets? This is needed to store the extracted color.

**Comment by piotrpog** [comment]
@roelvanhintum I didnt created any field. Its just a message that appears right after (during) installing of plugin.

**Comment by roelvanhintum** [comment]
@piotrpog The error should be gone in 2.0.0-beta.3. The imageColor field was missing, which prevents the plugin from working but should not throw errors and prevent installation. Installation should be fine now.
