### ISSUE TITLE
Image must be a gd resource

### ISSUE THREAD

**Issue by scandella** [born05/craft-colorextractor#6]
Hi,
I've got some ColorExtractorTask error in the Task manager but I'm unable to figure why.
It happen when the site editors users are creating some ressource entries.
I'm unable to reproduce this error.

The error message is "Image must be a gd resource".

When I manually upload the very same image file that cause the error, there is no such error and the Color Extractor Field is correctly populated.

How can I debug this?

Thanks for your help.

**Comment by roelvanhintum** [comment]
Is this still an issue since 2.1.0 and up?
